-- AUTO-GENERATED by tools/gen_datadoc.py, DO NOT EDIT
-- Source: Common/DataDoc/npc.xlsx
return {
    [1] = {
        id = 1,
        name = "史密斯铁匠",
        mapID = 1002,
        x = 100,
        z = 200,
        type = "npc",
        dialog = "npc/guide.lua",
    },
    [2] = {
        id = 2,
        name = "新手引导官",
        mapID = 1001,
        x = 50,
        z = 50,
        type = "npc",
        dialog = "npc/guide.lua",
    },
    [3] = {
        id = 3,
        name = "哥布林",
        mapID = 2001,
        x = 300,
        z = 400,
        type = "mob",
        ai = "npc/goblin_ai.lua",
    },
    [4] = {
        id = 4,
        name = "精英哥布林",
        mapID = 2001,
        x = 350,
        z = 420,
        type = "boss",
        ai = "npc/goblin_boss.lua",
    },
}
