-- AUTO-GENERATED by tools/gen_datadoc.py, DO NOT EDIT
-- Source: Common/DataDoc/quest.xlsx
return {
    [1001] = {
        id = 1001,
        name = "初出茅庐",
        desc = "消灭 5 只哥布林，收集耳朵",
        type = "kill",
        target = 3,
        itemID = 0,
        count = 5,
        reward = {
            exp = 500,
            gold = 100,
            itemID = 2001,
            itemCount = 1,
        },
    },
    [1002] = {
        id = 1002,
        name = "铁匠的委托",
        desc = "收集 10 块铁矿石",
        type = "collect",
        target = 0,
        itemID = 5001,
        count = 10,
        reward = {
            exp = 800,
            gold = 200,
            itemID = 3001,
            itemCount = 1,
        },
    },
}
