#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@file   gen_datadoc.py
@brief  将 Common/DataDoc/*.xlsx 策划表转换为 database/*.lua 供服务器加载

用法：
  python3 tools/gen_datadoc.py              # 转换全部 xlsx
  python3 tools/gen_datadoc.py --init       # 生成示例 Common/DataDoc/*.xlsx

表格式约定（每个 xlsx 取第一个工作表）：
  - 第 1 行：字段名（英文 camelCase，如 reward_exp 表示嵌套 reward.exp）
  - 第 2 行起：数据行；首列 id 为表主键
  - 空行或 id 为空则跳过
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    from openpyxl import Workbook, load_workbook
except ImportError:
    print(
        "缺少 openpyxl，请执行: pip3 install -r tools/requirements-datadoc.txt",
        file=sys.stderr,
    )
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
DATA_DOC_DIR = ROOT / "Common" / "DataDoc"
DATABASE_DIR = ROOT / "database"

# 输出模块名：npc.xlsx -> npc_config.lua -> require("npc_config")
OUTPUT_SUFFIX = "_config"

BOOL_TRUE = frozenset({"1", "true", "TRUE", "yes", "YES", "Y", "y"})
BOOL_FALSE = frozenset({"0", "false", "FALSE", "no", "NO", "N", "n"})


def toLuaValue(value: Any) -> str:
    """将单元格值格式化为 Lua 字面量。"""
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int,)):
        return str(value)
    if isinstance(value, float):
        if value.is_integer():
            return str(int(value))
        return repr(value)
    text = str(value).strip()
    if text == "":
        return '""'
    if text in BOOL_TRUE:
        return "true"
    if text in BOOL_FALSE:
        return "false"
    if re.fullmatch(r"-?\d+", text):
        return text
    if re.fullmatch(r"-?\d+\.\d+", text):
        return text
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def setNested(row: Dict[str, Any], key: str, value: Any) -> None:
    """按 a_b_c 字段名写入嵌套表。"""
    parts = [p for p in key.split("_") if p]
    if not parts:
        return
    if len(parts) == 1:
        row[parts[0]] = value
        return
    cur: Dict[str, Any] = row
    for part in parts[:-1]:
        if part not in cur or not isinstance(cur[part], dict):
            cur[part] = {}
        cur = cur[part]
    cur[parts[-1]] = value


def rowToRecord(headers: List[str], cells: List[Any]) -> Optional[Dict[str, Any]]:
    record: Dict[str, Any] = {}
    for idx, header in enumerate(headers):
        if not header:
            continue
        raw = cells[idx] if idx < len(cells) else None
        if raw is None or (isinstance(raw, str) and raw.strip() == ""):
            continue
        setNested(record, header.strip(), raw)
    if "id" not in record:
        return None
    record["id"] = int(record["id"]) if str(record["id"]).isdigit() else record["id"]
    return record


def emitLuaTable(records: Dict[Any, Dict[str, Any]], source: Path) -> str:
    lines = [
        "-- AUTO-GENERATED by tools/gen_datadoc.py, DO NOT EDIT",
        f"-- Source: {source.relative_to(ROOT).as_posix()}",
        "return {",
    ]
    for key in sorted(records.keys(), key=lambda k: (isinstance(k, str), k)):
        row = records[key]
        lines.append(f"    [{toLuaValue(key)}] = {{")
        for field, val in row.items():
            if isinstance(val, dict):
                lines.append(f"        {field} = {{")
                for subKey, subVal in val.items():
                    lines.append(f"            {subKey} = {toLuaValue(subVal)},")
                lines.append("        },")
            else:
                lines.append(f"        {field} = {toLuaValue(val)},")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def convertWorkbook(xlsxPath: Path) -> Path:
    wb = load_workbook(xlsxPath, data_only=True, read_only=True)
    sheet = wb.worksheets[0]
    rows = list(sheet.iter_rows(values_only=True))
    wb.close()
    if not rows:
        raise ValueError(f"{xlsxPath.name}: 工作表为空")

    headers = [str(h).strip() if h is not None else "" for h in rows[0]]
    if "id" not in headers:
        raise ValueError(f"{xlsxPath.name}: 首行必须包含 id 列")

    records: Dict[Any, Dict[str, Any]] = {}
    for rowCells in rows[1:]:
        if not rowCells or all(c is None or str(c).strip() == "" for c in rowCells):
            continue
        record = rowToRecord(headers, list(rowCells))
        if record is None:
            continue
        records[record["id"]] = record

    moduleName = xlsxPath.stem + OUTPUT_SUFFIX
    outPath = DATABASE_DIR / f"{moduleName}.lua"
    DATABASE_DIR.mkdir(parents=True, exist_ok=True)
    outPath.write_text(emitLuaTable(records, xlsxPath), encoding="utf-8")
    return outPath


def initSampleWorkbooks() -> None:
    """创建示例策划表（与 npc_mgr / quest_mgr 默认数据一致）。"""
    DATA_DOC_DIR.mkdir(parents=True, exist_ok=True)

    npcPath = DATA_DOC_DIR / "npc.xlsx"
    wbNpc = Workbook()
    wsNpc = wbNpc.active
    wsNpc.title = "npc"
    wsNpc.append(["id", "name", "mapID", "x", "z", "type", "dialog", "ai"])
    wsNpc.append([1, "史密斯铁匠", 1002, 100, 200, "npc", "npc/guide.lua", ""])
    wsNpc.append([2, "新手引导官", 1001, 50, 50, "npc", "npc/guide.lua", ""])
    wsNpc.append([3, "哥布林", 2001, 300, 400, "mob", "", "npc/goblin_ai.lua"])
    wsNpc.append([4, "精英哥布林", 2001, 350, 420, "boss", "", "npc/goblin_boss.lua"])
    wbNpc.save(npcPath)

    questPath = DATA_DOC_DIR / "quest.xlsx"
    wbQuest = Workbook()
    wsQuest = wbQuest.active
    wsQuest.title = "quest"
    wsQuest.append(
        [
            "id",
            "name",
            "desc",
            "type",
            "target",
            "itemID",
            "count",
            "reward_exp",
            "reward_gold",
            "reward_itemID",
            "reward_itemCount",
        ]
    )
    wsQuest.append(
        [
            1001,
            "初出茅庐",
            "消灭 5 只哥布林，收集耳朵",
            "kill",
            3,
            0,
            5,
            500,
            100,
            2001,
            1,
        ]
    )
    wsQuest.append(
        [
            1002,
            "铁匠的委托",
            "收集 10 块铁矿石",
            "collect",
            0,
            5001,
            10,
            800,
            200,
            3001,
            1,
        ]
    )
    wbQuest.save(questPath)

    mapPath = DATA_DOC_DIR / "map.xlsx"
    wbMap = Workbook()
    wsMap = wbMap.active
    wsMap.title = "map"
    wsMap.append(
        [
            "id",
            "name",
            "mapType",
            "maxPlayer",
            "enabled",
            "version",
            "addressableKey",
            "spawnX",
            "spawnY",
            "spawnZ",
        ]
    )
    wsMap.append([1001, "新手村", 1, 200, 1, 1, "map_1001", 0, 0, 0])
    wsMap.append([1002, "原野地图", 1, 500, 1, 1, "map_1002", 0, 0, 0])
    wsMap.append([1003, "仙侠主城", 1, 100, 1, 1, "map_1003", 0, 0, 5])
    wbMap.save(mapPath)

    print(f"[init] wrote {npcPath}")
    print(f"[init] wrote {questPath}")
    print(f"[init] wrote {mapPath}")


def main() -> int:
    parser = argparse.ArgumentParser(description="DataDoc Excel -> database Lua")
    parser.add_argument(
        "--init",
        action="store_true",
        help="生成示例 Common/DataDoc/*.xlsx（不执行转换）",
    )
    args = parser.parse_args()

    if args.init:
        initSampleWorkbooks()
        return 0

    if not DATA_DOC_DIR.is_dir():
        print(f"Common/DataDoc 目录不存在: {DATA_DOC_DIR}", file=sys.stderr)
        return 1

    xlsxFiles = sorted(DATA_DOC_DIR.glob("*.xlsx"))
    if not xlsxFiles:
        print("Common/DataDoc 下无 .xlsx，执行 --init 创建示例表")
        initSampleWorkbooks()
        xlsxFiles = sorted(DATA_DOC_DIR.glob("*.xlsx"))

    ok = 0
    for path in xlsxFiles:
        if path.name.startswith("~$"):
            continue
        try:
            out = convertWorkbook(path)
            print(f"[ok] {path.name} -> {out.relative_to(ROOT)}")
            ok += 1
        except Exception as exc:
            print(f"[fail] {path.name}: {exc}", file=sys.stderr)

    if ok == 0:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
